version: '3.7'
services:
  lumen-ala-nginx:
    build: ./docker/dev/nginx
    container_name: lumen-ala-nginx
    depends_on:
      - lumen-ala-php
    ports:
      - 8102:80
    volumes:
      - ./:/var/www/html

  lumen-ala-php:
    build: ./docker/dev/php-clear
    container_name: lumen-ala-php
    volumes:
      - ./:/var/www/html

  lumen-ala-mysql:
    image: mysql:8.0.22
    container_name: lumen-ala-mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=ala
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql-db:/docker-entrypoint-initdb.d
      - ./storage/.db:/var/lib/mysql
    security_opt:
      - seccomp:unconfined

  lumen-ala-redis:
    container_name: lumen-ala-redis
    image: redis:latest
    sysctls:
      net.core.somaxconn: 1024
    ports:
      - 6379:6379